name: Continuous integration

on:
  pull_request:
    types: ['opened', 'reopened', 'edited', 'synchronize']
    branches: ['develop', 'release', 'master', 'main']
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn
      - name: Install
        run: yarn --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
